# Example Site settings

#google_analytics: UA-NNNNNNNN-N
theme: jekyll-theme-console
header_pages:
  - index.md
  - blog.md
  - githubpage.md
  - contactme.md

footer: 'Follow me on <a href="https://twitter.com/thinksabin">twitter</a>'

style: dark # dark (default) or light

plugins:
  - jekyll-seo-tag
